# default: 공통Common 적용
# 'Spring' 이 고도화되면서 점차 properties 파일은 사용되지 않음
# 계층구조 표현으로 가독성이 더 좋고
# spring profiles 적용시 하나의 파일으로 해결이 가능
# dialect 방언 H2Dialect
# use_sql_comments 추가적인 주석 표시
# format_sql sql 이쁘게보기
# driver-class-name: org.h2.Driver
# org.hibernate.type: trace : 로그에있는 ? 값에 값 표시
# ddl-auto :
# 1. create : 항상 테이블 생성,
# 2. update : 수정된 스키마만 반영
# devtools : livereload - 개발용만 true, 실서버는 false, port 는 아무거나
# thymeleaf cache : false 수정 반영 즉각 반영, 운영모드는 true
# management.endpoints.web.exposure : actuator 가 포함할 endpoint 지정
spring:
  datasource:
    # url: jdbc:h2:tcp://localhost/~/test;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    # 카프카 로컬 테스트를 위해 인메모리 방식으로 변경
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
      port: 8008
    restart:
      enabled: true
  thymeleaf:
    cache: false


logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    org.hibernate.type: debug

management:
  endpoints:
    web:
      exposure:
        include: "metrics, prometheus"

# 카프카, 프로메테우스 테스트용 서버 포트 변경
#server:
#  port: 8100
---



# 운영서버 적용
#spring:
#  datasource:
#    url: jdbc:h2:~/.boot-spring-boot;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: validate
#  config:
#    activate:
#      on-profile: prod
#server:
#  port: 5000  # AWS Elastic Beanstalk 에서는 포트번호로 5000번을 사용해야한다.

