# default: 공통Common 적용
# Spring이 고도화되면서 점차 properties 파일은 사용되지 않음
# 계층구조 표현으로 가독성이 더 좋고
# spring profiles 적용시 하나의 파일으로 해결이 가능
# driver-class-name: org.h2.Driver
# ddl-auto :
# 1. create : 항상 테이블 생성,
# 2. updqte : 수정사항있으면 반영 없을시 생성

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug

---

# 운영서버 적용
#spring:
#  datasource:
#    url: jdbc:h2:~/.boot-spring-boot;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: validate
#  config:
#    activate:
#      on-profile: prod
#server:
#  port: 5000  # AWS Elastic Beanstalk 에서는 포트번호로 5000번을 사용해야한다.

